runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()

set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set paste
set autoindent

set nu

colorscheme evening 
filetype plugin indent on

"close omnicomplete window when moving cursor
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#Complete
